#!/bin/sh
STAGE_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.vue' '*.js')
set -x

PASS=true
for FILE in $STAGE_FILES
do
    ./node_modules/.bin/eslint $FILE
    if [[ "$?" == 1 ]]; then
        PASS=false
    fi
done

if ! $PASS; then
  echo "lint running failed！"
  exit 1
fi
